version: '3.8'

services:
  # --- DATA LAKE (MinIO) ---
  datalake:
    image: minio/minio:latest
    container_name: datalake_minio
    hostname: datalake
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio_data:/data
    networks:
      - datamasters_net

  # --- SPARK MASTER (Imagem Oficial Apache) ---
  spark:
    image: apache/spark:3.5.0
    container_name: spark_master
    hostname: spark
    user: root 
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./:/app
    working_dir: /app
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    networks:
      - datamasters_net

  # --- SPARK WORKER (Imagem Oficial Apache) ---
  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark_worker
    user: root
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark:7077
    networks:
      - datamasters_net

networks:
  datamasters_net:
    driver: bridge